#include "AchievementSystem.h"

const std::unordered_map<Achievement, AchievementText> AchievementTextData = {
		{ Achievement::Artemis_friendly,  { "Friendly fire",       "Shoot your own squid 100 times." }},
		{ Achievement::Artemis_sharp,     { "Marksman",            "Win without shooting your own squid." }},
		{ Achievement::Bee_b,             { "Flapper 1",           "Score 50 points." }},
		{ Achievement::Bee_s,             { "Flapper 2",           "Score 100 points." }},
		{ Achievement::Bee_g,             { "Flapper 3",           "Score 200 points." }},
		{ Achievement::Blocks_clear,      { "Clean slate",         "Completely clear the field." }},
		{ Achievement::Blocks_b,          { "Blokker 1",           "Score 500 points." }},
		{ Achievement::Blocks_s,          { "Blokker 2",           "Score 1000 points." }},
		{ Achievement::Blocks_g,          { "Blokker 3",           "Score 2000 points." }},
		{ Achievement::Bob_bombs,         { "No bombs",            "Win without eating any bombs." }},
		{ Achievement::Bonk_5,            { "Undisputed",          "Win 5 games in a row." }},
		{ Achievement::Bonk_comeback,     { "Comeback",            "Win after losing 0-2." }},
		{ Achievement::Buttons_win,       { "Moves like Jagger",   "Win without missing a single beat." }},
		{ Achievement::Capacitron_b,      { "Jumper 1",            "Score 50 points." }},
		{ Achievement::Capacitron_s,      { "Jumper 2",            "Score 100 points." }},
		{ Achievement::Capacitron_g,      { "Jumper 3",            "Score 200 points." }},
		{ Achievement::Capacitron_fire,   { "Firebender",          "Eat a fireball after getting a potion." }},
		{ Achievement::Dusty_rat,         { "Recharge",            "Lose a battery to a rat." }},
		{ Achievement::Hertz_3,           { "Optimal tuning",      "Win in three hits." }},
		{ Achievement::Marv_5,            { "Pro runner",          "Win 5 times in a row without losing any lives." }},
		{ Achievement::Marv_life,         { "Runner",              "Win once without losing any lives." }},
		{ Achievement::Planck_b,          { "Novice driver",       "Score 10 points." }},
		{ Achievement::Planck_g,          { "Expert driver",       "Score 50 points." }},
		{ Achievement::Planck_juice,      { "More juice",          "Collect 10 batteries in a single run." }},
		{ Achievement::Planck_s,          { "Intermediate driver", "Score 20 points." }},
		{ Achievement::Resistron_b,       { "Space guardian 1",    "Score 50 points." }},
		{ Achievement::Resistron_s,       { "Space guardian 2",    "Score 100 points." }},
		{ Achievement::Resistron_g,       { "Space guardian 3",    "Score 200 points." }},
		{ Achievement::Resistron_deflect, { "Parry",               "Deflect an enemy bullet with your own." }},
		{ Achievement::Robby_asteroid,    { "Kessel Run",          "Win without colliding with an asteroid." }},
		{ Achievement::Robby_sharp,       { "Sharp shooter",       "Don't miss a single shot." }},
		{ Achievement::Snake_b,           { "Snaker 1",            "Score 10 points." }},
		{ Achievement::Snake_s,           { "Snaker 2",            "Score 50 points." }},
		{ Achievement::Snake_g,           { "Snaker 3",            "Score 100 points." }},
		{ Achievement::Snake_fill,        { "Snake pro",           "Reach maximum snake length." }},
		{ Achievement::Sparkly_nobrake,   { "Racer",               "Win without braking." }},
		{ Achievement::Sparkly_road,      { "Invincible",          "Complete a run without hitting the barrier." }},
		{ Achievement::Stacky_5,          { "Architect",           "Get 5 perfect drops in a row." }},
		{ Achievement::Stacky_highrise,   { "Highrise",            "Reach a height of 50 blocks." }},
		{ Achievement::Stacky_skyscraper, { "Skyscraper",          "Reach a height of 100 blocks." }},
		{ Achievement::Stacky_super,      { "Mega structure",      "Reach a height of 200 blocks." }},
		// { Achievement::Bee_crow,         { "Crow hopper",       "Fly over a crow" }},
		// { Achievement::Blocks// _4lines,     { "Blocks!",             "Clear 4 lines at once" }},
		// { Achievement::Bob_green,        { "Green gourmet",     "Win while eating only green bulbs" }},
		// { Achievement::Bob_yellow,       { "Red gourmet",       "Win while eating only red bulbs" }},
		// { Achievement::Buttons_triple,   { "Hips don't lie",    "Win while hitting every triple note" }},
		// { Achievement::Charlie_nomercy,   { "No mercy",            "Win without letting a trapped fly escape." }},
		// { Achievement::Charlie_yesmercy,  { "Mercy",           "Lose every trapped fly" }},
		// { Achievement::Dusty_shovel,      { "Expert excavator",    "Win without losing a life" }},
		// { Achievement::Fred_copper,       { "Copper",              "Catch all criminals with a single pair of handcuffs" }},
		// { Achievement::Fred_detective,    { "Detective",           "Collect all tracks in a level without losing a life" }},
		// { Achievement::Fred_veteran,      { "Veteran",             "Catch 100 criminals" }},
		// { Achievement::Marv_newspapers,   { "Paperboy",            "Get hit by newspapers 100 times" }},
		// { Achievement::Planck_chauffeur,  { "Chauffeur",           "Win without hitting a single obstacle" }},
		// { Achievement::Planck_nobrake,    { "Joyride",             "Complete a run without braking once" }},
		// { Achievement::Sparkly_overtake,  { "",                    "Don't get overtaken a single time." }},
};
